### ISSUE TITLE
Thoughts on hiding email addresses in Slack? 

### ISSUE THREAD

**Issue by discentem** [Gear61/Tech-Career-Growth-Learning-Resources-And-Roadmaps#11]
Apologies if this is the wrong place for this but I did not find any `#ask-about-this-slack` sort of channel in the actual Slack community. 

What are your thoughts on [hiding email addresses](https://slack.com/help/articles/228020667-Manage-email-display) from users' profiles? Was it a conscious decision to keep it on? If so, do you mind saying why? 

One benefit to turning this off: people may feel more free to ask questions without fear or attribution across the entire internet. 

Downside: this might make it easier for bad actors to spam, etc given that it won't be obvious what email their account is associated with.

**Comment by rpandey1234** [comment]
Thanks for bringing this up, it wasn't a conscious decision by Alex or me to leave emails visible (we kept the defaults).

As the community gets bigger, we definitely want to ensure that people feel safe asking questions and their private info won't get abused. 

I just flipped the setting as per your link, thank you for pointing this out 🙏🏽

**Comment by discentem** [comment]
It's worth noting for anyone who happens upon this issue over the next few days/weeks: you must relaunch or reload the slack desktop client to see the email field disappear.
