### ISSUE TITLE
I want to propose creating a documentation site out of this repository

### ISSUE THREAD

**Issue by tamalweb** [Gear61/Tech-Career-Growth-Learning-Resources-And-Roadmaps#12]
This could be a documentation site or a blog which will make it easier to navigate and find out all the content from this repo.

For a trial run, I want to copy a handful of posts from this repo and make an MVP.

Thoughts?

**Comment by rafatmunshi** [comment]
I think this is a great idea. To begin with, it could be as simple as hosting the code files in this same repo which would access the other files and images and display them suitably on the site with GitHub pages.

**Comment by Gear61** [comment]
@tamalweb If you have the time, you should totally do this! A GitHub repo isn't particularly welcoming as it places the burden on the user to go through the pages and pages of content to find what they want. A website that takes on that burden (can be through search, personalization, or maybe an assistant-like interface) would be cool. Right now, we have techcareergrowth.co to help with that, but I think Eric is too busy to maintain it right now and that's more for official resources that Rahul and I have made as opposed to this repo which has everything.

**Comment by tamalweb** [comment]
Hey, all thanks for the feedback, I will get working on that in my spare time, and then show you how to convert the posts into the doc pages, it will be easy because it works with Markdown syntax.

Do we have a TechCareerGrowth organization here on GitHub? Have you thought about making one and publish that doc under the org? 

Thanks.

**Comment by Gear61** [comment]
Nope, there isn't a Tech Career Growth organization on GitHub. @rpandey1234 and I are just wary of creating more entities that we then have to manage.

**Comment by spattk** [comment]
@Gear61, but another org would be a lot cleaner.
I would love to manage the TCG Github org if you wish. 

And you guys can definitely reach out to the awesome TCG community for managing different things until you have things laid out as per your bigger vision where you can actually hire someone to be a community manager.

Thanks!

**Comment by tamalweb** [comment]
Agree with @Gear61 on limiting entities. I will push this blog in this repo and see how that goes.
