### ISSUE TITLE
Text instead of images

### ISSUE THREAD

**Issue by veganaize** [Gear61/Tech-Career-Growth-Learning-Resources-And-Roadmaps#3]
@Gear61 if you'd prefer, I can import the respective text that's in those images (in 'threads').

**Comment by Gear61** [comment]
Yeah, let's standardize everything to text. My concern is that having a lot of posts in the README is going to make it overwhelmingly long. Thinking we can link to thread files which are text from the master README? And then make sure they have nice descriptive titles obviously.

**Comment by rafatmunshi** [comment]
I think we can do that. It would be good to keep things in the readme as an index of links per topic to a series of articles for further reading.
