### ISSUE TITLE
To post or not to post

### ISSUE THREAD

**Issue by veganaize** [Gear61/Tech-Career-Growth-Learning-Resources-And-Roadmaps#4]
I've been a little hesitant to bring over posts because they're often part of some thread, and not in an article format, so I'm on the fence about whether or not I should edit them, or chop them up, or leave them as-is...?

**Comment by rafatmunshi** [comment]
I would suggest, we can change the words a bit just to add context and make it as an article so it is valuable for a reader. That is what I had done to add the post in the readme. Just changed some words and it made sense.

**Comment by veganaize** [comment]
Should we place the changes inside of [square brackets] to indicate the edit?

**Comment by Gear61** [comment]
I'm fine either way on the editing thing. We shouldn't overthink this.

**Comment by veganaize** [comment]
I wouldn't want my name/photo next to anything I didn't say -- unless it was obvious that an edit was made.  That's where I'm coming from.

**Comment by Gear61** [comment]
@veganaize Makes sense, I like the square brackets then :)
